spring:
  application:
    name: cdd-gateway
  profiles:
    active: ${CDD_ENV:local}

cdd:
  runtime:
    config-mode: ${CDD_CONFIG_MODE:file}
  security:
    permit-all: false
    permit-paths:
      - /actuator/health
      - /actuator/info
    jwt:
      issuer: cdd-auth-service
      secret: chengdd-jwt-secret-change-me-20260321-123456
      access-token-ttl: 30m
      refresh-token-ttl: 7d

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
