SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `cdd_merchant_application` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `merchant_name` varchar(128) NOT NULL COMMENT '商家主体名称',
  `merchant_type` varchar(32) NOT NULL COMMENT '商家类型：enterprise/individual',
  `contact_name` varchar(64) NOT NULL COMMENT '联系人',
  `contact_mobile` varchar(32) NOT NULL COMMENT '联系电话',
  `legal_person_name` varchar(64) NOT NULL COMMENT '法人姓名',
  `business_category` varchar(64) NOT NULL COMMENT '经营类目',
  `brand_name` varchar(128) DEFAULT NULL COMMENT '品牌名称',
  `license_file_url` varchar(512) NOT NULL COMMENT '营业执照地址',
  `status` varchar(32) NOT NULL COMMENT '申请状态',
  `reject_reason` varchar(512) DEFAULT NULL COMMENT '驳回原因',
  `submitted_at` datetime DEFAULT NULL COMMENT '提交时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_contact_mobile_deleted` (`contact_mobile`, `deleted`),
  KEY `idx_status_submitted_at` (`status`, `submitted_at`),
  KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商家入驻申请表';

CREATE TABLE IF NOT EXISTS `cdd_merchant_profile` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `merchant_no` varchar(32) NOT NULL COMMENT '商家编号',
  `merchant_name` varchar(128) NOT NULL COMMENT '商家名称',
  `merchant_type` varchar(32) NOT NULL COMMENT '商家类型',
  `brand_name` varchar(128) DEFAULT NULL COMMENT '品牌名称',
  `status` varchar(32) NOT NULL COMMENT '商家状态',
  `current_application_id` bigint DEFAULT NULL COMMENT '当前申请ID',
  `contact_name` varchar(64) NOT NULL COMMENT '联系人',
  `contact_mobile` varchar(32) NOT NULL COMMENT '联系电话',
  `business_scope` varchar(512) DEFAULT NULL COMMENT '经营范围',
  `settled_at` datetime DEFAULT NULL COMMENT '入驻时间',
  `remark` varchar(512) DEFAULT NULL COMMENT '备注',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_merchant_no_deleted` (`merchant_no`, `deleted`),
  UNIQUE KEY `uk_merchant_name_deleted` (`merchant_name`, `deleted`),
  KEY `idx_status` (`status`),
  KEY `idx_contact_mobile` (`contact_mobile`),
  KEY `idx_current_application_id` (`current_application_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商家主体资料表';

CREATE TABLE IF NOT EXISTS `cdd_merchant_store` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `merchant_id` bigint NOT NULL COMMENT '商家ID',
  `store_no` varchar(32) NOT NULL COMMENT '店铺编号',
  `store_name` varchar(128) NOT NULL COMMENT '店铺名称',
  `logo_url` varchar(512) DEFAULT NULL COMMENT '店铺Logo',
  `description` varchar(1024) DEFAULT NULL COMMENT '店铺简介',
  `business_status` varchar(32) NOT NULL COMMENT '营业状态',
  `shipping_sla_hours` int DEFAULT NULL COMMENT '履约时效小时数',
  `customer_service_type` varchar(32) DEFAULT NULL COMMENT '客服类型',
  `customer_service_value` varchar(128) DEFAULT NULL COMMENT '客服值',
  `return_address` varchar(512) DEFAULT NULL COMMENT '退货地址',
  `service_commitment` varchar(1024) DEFAULT NULL COMMENT '服务承诺',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_store_no_deleted` (`store_no`, `deleted`),
  UNIQUE KEY `uk_merchant_store_name_deleted` (`merchant_id`, `store_name`, `deleted`),
  KEY `idx_merchant_id` (`merchant_id`),
  KEY `idx_merchant_status` (`merchant_id`, `business_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商家店铺表';

CREATE TABLE IF NOT EXISTS `cdd_merchant_mini_program` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `merchant_id` bigint NOT NULL COMMENT '商家ID',
  `store_id` bigint NOT NULL COMMENT '店铺ID',
  `app_id` varchar(64) NOT NULL COMMENT '小程序AppID',
  `app_secret_masked` varchar(128) DEFAULT NULL COMMENT '脱敏后的AppSecret',
  `payment_mch_id` varchar(64) DEFAULT NULL COMMENT '支付商户号',
  `server_domain` varchar(256) DEFAULT NULL COMMENT '服务域名',
  `binding_status` varchar(32) NOT NULL COMMENT '绑定状态',
  `current_template_version` varchar(64) DEFAULT NULL COMMENT '当前模板版本',
  `last_detect_result_json` json DEFAULT NULL COMMENT '最近检测结果',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_app_id_deleted` (`app_id`, `deleted`),
  KEY `idx_merchant_store` (`merchant_id`, `store_id`),
  KEY `idx_binding_status` (`binding_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商家小程序接入配置表';

CREATE TABLE IF NOT EXISTS `cdd_merchant_sub_account` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `merchant_id` bigint NOT NULL COMMENT '商家ID',
  `account_name` varchar(64) NOT NULL COMMENT '登录账号',
  `display_name` varchar(64) NOT NULL COMMENT '显示名称',
  `mobile` varchar(32) DEFAULT NULL COMMENT '手机号',
  `status` varchar(32) NOT NULL COMMENT '账号状态',
  `role_label` varchar(64) DEFAULT NULL COMMENT '角色标签',
  `password_hash` varchar(256) DEFAULT NULL COMMENT '密码哈希',
  `last_login_at` datetime DEFAULT NULL COMMENT '最后登录时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_account_name_deleted` (`account_name`, `deleted`),
  UNIQUE KEY `uk_mobile_deleted` (`mobile`, `deleted`),
  KEY `idx_merchant_id` (`merchant_id`),
  KEY `idx_merchant_status` (`merchant_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商家子账号表';

CREATE TABLE IF NOT EXISTS `cdd_merchant_account_scope` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `merchant_id` bigint NOT NULL COMMENT '商家ID',
  `account_id` bigint NOT NULL COMMENT '账号ID',
  `scope_type` varchar(32) NOT NULL COMMENT '范围类型',
  `scope_object_type` varchar(32) NOT NULL COMMENT '对象类型',
  `scope_object_id` bigint NOT NULL COMMENT '对象ID',
  `action_permissions_json` json DEFAULT NULL COMMENT '动作权限集合',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  KEY `idx_account_id` (`account_id`),
  KEY `idx_scope_object` (`scope_object_type`, `scope_object_id`),
  KEY `idx_account_scope` (`account_id`, `scope_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商家子账号数据范围表';
