SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `cdd_decoration_home_config` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `merchant_id` bigint NOT NULL COMMENT '商家ID',
  `store_id` bigint NOT NULL COMMENT '店铺ID',
  `mini_program_id` bigint NOT NULL COMMENT '小程序ID',
  `home_template_code` varchar(64) NOT NULL COMMENT '首页模板编码',
  `home_style_mode` varchar(32) DEFAULT NULL COMMENT '首页风格模式',
  `theme_color` varchar(32) DEFAULT NULL COMMENT '主题色',
  `search_placeholder` varchar(128) DEFAULT NULL COMMENT '搜索占位文案',
  `header_service_bar_json` json DEFAULT NULL COMMENT '顶部服务条',
  `brand_hero_block_json` json DEFAULT NULL COMMENT '头图配置',
  `delivery_promise_text` varchar(128) DEFAULT NULL COMMENT '配送承诺文案',
  `delivery_fee_text` varchar(64) DEFAULT NULL COMMENT '配送费文案',
  `minimum_order_text` varchar(64) DEFAULT NULL COMMENT '起送价文案',
  `announcement_text` varchar(512) DEFAULT NULL COMMENT '公告文案',
  `status` varchar(32) NOT NULL COMMENT '配置状态',
  `version_no` int NOT NULL DEFAULT '1' COMMENT '版本号',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_store_mini_program_deleted` (`store_id`, `mini_program_id`, `deleted`),
  KEY `idx_merchant_store` (`merchant_id`, `store_id`),
  KEY `idx_status_version` (`status`, `version_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='首页装修主配置表';

CREATE TABLE IF NOT EXISTS `cdd_decoration_home_module` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `merchant_id` bigint NOT NULL COMMENT '商家ID',
  `store_id` bigint NOT NULL COMMENT '店铺ID',
  `home_config_id` bigint NOT NULL COMMENT '首页配置ID',
  `module_type` varchar(64) NOT NULL COMMENT '模块类型',
  `module_name` varchar(128) NOT NULL COMMENT '模块名称',
  `sort_order` int NOT NULL DEFAULT '0' COMMENT '排序号',
  `is_enabled` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否启用',
  `style_mode` varchar(32) DEFAULT NULL COMMENT '模块风格',
  `data_source_type` varchar(32) DEFAULT NULL COMMENT '数据源类型',
  `data_source_id` bigint DEFAULT NULL COMMENT '数据源ID',
  `jump_target_json` json DEFAULT NULL COMMENT '跳转配置',
  `config_payload_json` json DEFAULT NULL COMMENT '模块配置',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  KEY `idx_home_config_sort` (`home_config_id`, `sort_order`),
  KEY `idx_home_config_enabled` (`home_config_id`, `is_enabled`),
  KEY `idx_module_type` (`module_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='首页装修模块表';

CREATE TABLE IF NOT EXISTS `cdd_decoration_home_version` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `merchant_id` bigint NOT NULL COMMENT '商家ID',
  `store_id` bigint NOT NULL COMMENT '店铺ID',
  `home_config_id` bigint NOT NULL COMMENT '首页配置ID',
  `version_no` int NOT NULL COMMENT '版本号',
  `version_status` varchar(32) NOT NULL COMMENT '版本状态',
  `snapshot_json` json NOT NULL COMMENT '配置快照',
  `published_at` datetime DEFAULT NULL COMMENT '发布时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  KEY `idx_home_config_version` (`home_config_id`, `version_no`),
  KEY `idx_home_config_status` (`home_config_id`, `version_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='首页装修版本记录表';

CREATE TABLE IF NOT EXISTS `cdd_decoration_template_binding` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `merchant_id` bigint NOT NULL COMMENT '商家ID',
  `store_id` bigint NOT NULL COMMENT '店铺ID',
  `mini_program_id` bigint NOT NULL COMMENT '小程序ID',
  `template_code` varchar(64) NOT NULL COMMENT '模板编码',
  `style_mode` varchar(32) DEFAULT NULL COMMENT '风格模式',
  `binding_status` varchar(32) NOT NULL COMMENT '绑定状态',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_store_template_deleted` (`store_id`, `mini_program_id`, `template_code`, `deleted`),
  KEY `idx_merchant_store` (`merchant_id`, `store_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='首页模板绑定表';
