SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `cdd_product_category_template` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `template_name` varchar(128) NOT NULL COMMENT '模板名称',
  `industry_code` varchar(64) NOT NULL COMMENT '行业编码',
  `template_version` varchar(32) NOT NULL COMMENT '模板版本',
  `max_level` int NOT NULL DEFAULT '3' COMMENT '最大层级',
  `status` varchar(32) NOT NULL COMMENT '模板状态',
  `default_sort_rule` varchar(64) DEFAULT NULL COMMENT '默认排序规则',
  `template_desc` varchar(512) DEFAULT NULL COMMENT '模板说明',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_template_name_version_deleted` (`template_name`, `template_version`, `deleted`),
  KEY `idx_industry_status` (`industry_code`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='平台分类模板表';

CREATE TABLE IF NOT EXISTS `cdd_product_category_template_attribute` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `template_id` bigint NOT NULL COMMENT '模板ID',
  `attribute_code` varchar(64) NOT NULL COMMENT '属性编码',
  `attribute_name` varchar(128) NOT NULL COMMENT '属性名称',
  `value_type` varchar(32) NOT NULL COMMENT '值类型',
  `is_required` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否必填',
  `is_sale_attribute` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否销售属性',
  `option_values_json` json DEFAULT NULL COMMENT '候选值',
  `sort_order` int NOT NULL DEFAULT '0' COMMENT '排序号',
  `status` varchar(32) NOT NULL COMMENT '状态',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_template_attr_code_deleted` (`template_id`, `attribute_code`, `deleted`),
  KEY `idx_template_sort` (`template_id`, `sort_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='分类模板属性表';

CREATE TABLE IF NOT EXISTS `cdd_product_category` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `merchant_id` bigint NOT NULL COMMENT '商家ID',
  `store_id` bigint DEFAULT NULL COMMENT '店铺ID',
  `template_id` bigint DEFAULT NULL COMMENT '来源模板ID',
  `parent_id` bigint NOT NULL DEFAULT '0' COMMENT '父分类ID',
  `category_name` varchar(128) NOT NULL COMMENT '分类名称',
  `category_icon_url` varchar(512) DEFAULT NULL COMMENT '分类图标',
  `category_level` int NOT NULL DEFAULT '1' COMMENT '分类层级',
  `sort_order` int NOT NULL DEFAULT '0' COMMENT '排序号',
  `is_enabled` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否启用',
  `is_visible` tinyint(1) NOT NULL DEFAULT '1' COMMENT '前台是否可见',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_merchant_parent_name_deleted` (`merchant_id`, `parent_id`, `category_name`, `deleted`),
  KEY `idx_merchant_parent` (`merchant_id`, `parent_id`),
  KEY `idx_merchant_enabled` (`merchant_id`, `is_enabled`),
  KEY `idx_merchant_visible` (`merchant_id`, `is_visible`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商家分类表';

CREATE TABLE IF NOT EXISTS `cdd_product_category_attribute` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `category_id` bigint NOT NULL COMMENT '分类ID',
  `attribute_code` varchar(64) NOT NULL COMMENT '属性编码',
  `attribute_name` varchar(128) NOT NULL COMMENT '属性名称',
  `value_type` varchar(32) NOT NULL COMMENT '值类型',
  `is_required` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否必填',
  `is_sale_attribute` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否销售属性',
  `option_values_json` json DEFAULT NULL COMMENT '候选值',
  `sort_order` int NOT NULL DEFAULT '0' COMMENT '排序号',
  `status` varchar(32) NOT NULL COMMENT '状态',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_category_attr_code_deleted` (`category_id`, `attribute_code`, `deleted`),
  KEY `idx_category_sort` (`category_id`, `sort_order`),
  KEY `idx_category_status` (`category_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商家分类属性表';

CREATE TABLE IF NOT EXISTS `cdd_product_spu` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `merchant_id` bigint NOT NULL COMMENT '商家ID',
  `store_id` bigint NOT NULL COMMENT '店铺ID',
  `category_id` bigint NOT NULL COMMENT '分类ID',
  `product_name` varchar(256) NOT NULL COMMENT '商品名称',
  `product_sub_title` varchar(256) DEFAULT NULL COMMENT '副标题',
  `main_image_url` varchar(512) DEFAULT NULL COMMENT '主图',
  `media_gallery_json` json DEFAULT NULL COMMENT '图文素材',
  `product_desc` text COMMENT '商品描述',
  `status` varchar(32) NOT NULL COMMENT '商品状态',
  `publish_check_status` varchar(32) NOT NULL COMMENT '发布检查状态',
  `sale_label_json` json DEFAULT NULL COMMENT '卖点标签',
  `delivery_type` varchar(32) DEFAULT NULL COMMENT '配送类型',
  `sort_order` int NOT NULL DEFAULT '0' COMMENT '排序号',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_store_product_name_deleted` (`store_id`, `product_name`, `deleted`),
  KEY `idx_store_category_status` (`store_id`, `category_id`, `status`),
  KEY `idx_store_publish_status` (`store_id`, `publish_check_status`),
  KEY `idx_merchant_created_at` (`merchant_id`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商品SPU表';

CREATE TABLE IF NOT EXISTS `cdd_product_sku` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `merchant_id` bigint NOT NULL COMMENT '商家ID',
  `store_id` bigint NOT NULL COMMENT '店铺ID',
  `product_id` bigint NOT NULL COMMENT '商品ID',
  `sku_code` varchar(64) NOT NULL COMMENT 'SKU编码',
  `sku_name` varchar(256) NOT NULL COMMENT 'SKU名称',
  `spec_json` json DEFAULT NULL COMMENT '规格组合',
  `sale_price` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '销售价',
  `market_price` decimal(10,2) DEFAULT NULL COMMENT '划线价',
  `cost_price` decimal(10,2) DEFAULT NULL COMMENT '成本价',
  `weight_gram` int DEFAULT NULL COMMENT '重量克',
  `volume_json` json DEFAULT NULL COMMENT '体积信息',
  `status` varchar(32) NOT NULL COMMENT 'SKU状态',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sku_code_deleted` (`sku_code`, `deleted`),
  KEY `idx_product_id` (`product_id`),
  KEY `idx_product_status` (`product_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商品SKU表';

CREATE TABLE IF NOT EXISTS `cdd_product_stock` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `merchant_id` bigint NOT NULL COMMENT '商家ID',
  `store_id` bigint NOT NULL COMMENT '店铺ID',
  `product_id` bigint NOT NULL COMMENT '商品ID',
  `sku_id` bigint NOT NULL COMMENT 'SKU ID',
  `available_stock` int NOT NULL DEFAULT '0' COMMENT '可售库存',
  `locked_stock` int NOT NULL DEFAULT '0' COMMENT '锁定库存',
  `warning_stock` int DEFAULT NULL COMMENT '预警库存',
  `stock_status` varchar(32) NOT NULL COMMENT '库存状态',
  `last_stock_in_at` datetime DEFAULT NULL COMMENT '最近入库时间',
  `last_stock_out_at` datetime DEFAULT NULL COMMENT '最近出库时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sku_id_deleted` (`sku_id`, `deleted`),
  KEY `idx_product_id` (`product_id`),
  KEY `idx_merchant_sku` (`merchant_id`, `sku_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商品库存表';

CREATE TABLE IF NOT EXISTS `cdd_product_publish_record` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `merchant_id` bigint NOT NULL COMMENT '商家ID',
  `store_id` bigint NOT NULL COMMENT '店铺ID',
  `product_id` bigint NOT NULL COMMENT '商品ID',
  `mini_program_id` bigint DEFAULT NULL COMMENT '小程序ID',
  `publish_result` varchar(32) NOT NULL COMMENT '发布结果',
  `publish_message` varchar(512) DEFAULT NULL COMMENT '发布信息',
  `published_at` datetime DEFAULT NULL COMMENT '发布时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  KEY `idx_product_created_at` (`product_id`, `created_at`),
  KEY `idx_store_result` (`store_id`, `publish_result`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商品发布记录表';

CREATE TABLE IF NOT EXISTS `cdd_product_attribute_snapshot` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `product_id` bigint NOT NULL COMMENT '商品ID',
  `attribute_id` bigint NOT NULL COMMENT '属性ID',
  `attribute_code` varchar(64) NOT NULL COMMENT '属性编码',
  `attribute_name` varchar(128) NOT NULL COMMENT '属性名称',
  `attribute_value_json` json DEFAULT NULL COMMENT '属性值快照',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  KEY `idx_product_id` (`product_id`),
  KEY `idx_product_attribute` (`product_id`, `attribute_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商品属性快照表';
