SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `cdd_order_cart_item` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `merchant_id` bigint NOT NULL COMMENT '商家ID',
  `store_id` bigint NOT NULL COMMENT '店铺ID',
  `user_id` bigint NOT NULL COMMENT '用户ID',
  `product_id` bigint NOT NULL COMMENT '商品ID',
  `sku_id` bigint NOT NULL COMMENT 'SKU ID',
  `quantity` int NOT NULL DEFAULT '1' COMMENT '购买数量',
  `selected` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否选中',
  `snapshot_price` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '加入时价格快照',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_store_sku_deleted` (`user_id`, `store_id`, `sku_id`, `deleted`),
  KEY `idx_user_store_selected` (`user_id`, `store_id`, `selected`),
  KEY `idx_merchant_user` (`merchant_id`, `user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='购物车明细表';

CREATE TABLE IF NOT EXISTS `cdd_order_checkout_snapshot` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `merchant_id` bigint NOT NULL COMMENT '商家ID',
  `store_id` bigint NOT NULL COMMENT '店铺ID',
  `user_id` bigint NOT NULL COMMENT '用户ID',
  `snapshot_token` varchar(64) NOT NULL COMMENT '结算快照令牌',
  `cart_item_ids_json` json DEFAULT NULL COMMENT '购物车项ID列表',
  `pricing_snapshot_json` json NOT NULL COMMENT '试算快照',
  `address_snapshot_json` json DEFAULT NULL COMMENT '地址快照',
  `coupon_snapshot_json` json DEFAULT NULL COMMENT '优惠快照',
  `expired_at` datetime NOT NULL COMMENT '过期时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_snapshot_token_deleted` (`snapshot_token`, `deleted`),
  KEY `idx_user_expired` (`user_id`, `expired_at`),
  KEY `idx_store_created_at` (`store_id`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='结算快照表';

CREATE TABLE IF NOT EXISTS `cdd_order_info` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `order_no` varchar(32) NOT NULL COMMENT '订单号',
  `merchant_id` bigint NOT NULL COMMENT '商家ID',
  `store_id` bigint NOT NULL COMMENT '店铺ID',
  `user_id` bigint NOT NULL COMMENT '用户ID',
  `checkout_snapshot_id` bigint DEFAULT NULL COMMENT '结算快照ID',
  `order_status` varchar(32) NOT NULL COMMENT '订单状态',
  `pay_status` varchar(32) NOT NULL COMMENT '支付状态',
  `delivery_status` varchar(32) DEFAULT NULL COMMENT '履约状态',
  `buyer_remark` varchar(512) DEFAULT NULL COMMENT '买家备注',
  `total_amount` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '订单总金额',
  `discount_amount` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '优惠金额',
  `payable_amount` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '应付金额',
  `paid_amount` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '实付金额',
  `delivery_fee_amount` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '配送费',
  `receiver_name` varchar(64) DEFAULT NULL COMMENT '收货人',
  `receiver_mobile` varchar(32) DEFAULT NULL COMMENT '收货手机号',
  `receiver_address` varchar(512) DEFAULT NULL COMMENT '收货地址',
  `paid_at` datetime DEFAULT NULL COMMENT '支付时间',
  `cancelled_at` datetime DEFAULT NULL COMMENT '取消时间',
  `finished_at` datetime DEFAULT NULL COMMENT '完成时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_order_no_deleted` (`order_no`, `deleted`),
  KEY `idx_user_created_at` (`user_id`, `created_at`),
  KEY `idx_store_status_created` (`store_id`, `order_status`, `created_at`),
  KEY `idx_merchant_pay_status` (`merchant_id`, `pay_status`),
  KEY `idx_store_pay_status` (`store_id`, `pay_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单主表';

CREATE TABLE IF NOT EXISTS `cdd_order_item` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `order_id` bigint NOT NULL COMMENT '订单ID',
  `merchant_id` bigint NOT NULL COMMENT '商家ID',
  `store_id` bigint NOT NULL COMMENT '店铺ID',
  `product_id` bigint NOT NULL COMMENT '商品ID',
  `sku_id` bigint NOT NULL COMMENT 'SKU ID',
  `product_name` varchar(256) NOT NULL COMMENT '商品名称快照',
  `sku_name` varchar(256) NOT NULL COMMENT 'SKU名称快照',
  `sku_spec_json` json DEFAULT NULL COMMENT 'SKU规格快照',
  `sale_price` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '成交单价',
  `quantity` int NOT NULL DEFAULT '1' COMMENT '购买数量',
  `line_amount` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '行金额',
  `refund_status` varchar(32) DEFAULT NULL COMMENT '退款状态',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  KEY `idx_order_id` (`order_id`),
  KEY `idx_product_id` (`product_id`),
  KEY `idx_sku_id` (`sku_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单商品明细表';

CREATE TABLE IF NOT EXISTS `cdd_order_pay_record` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `pay_no` varchar(32) NOT NULL COMMENT '支付单号',
  `order_id` bigint NOT NULL COMMENT '订单ID',
  `order_no` varchar(32) NOT NULL COMMENT '订单号',
  `merchant_id` bigint NOT NULL COMMENT '商家ID',
  `store_id` bigint NOT NULL COMMENT '店铺ID',
  `pay_channel` varchar(32) NOT NULL COMMENT '支付渠道',
  `pay_method` varchar(32) DEFAULT NULL COMMENT '支付方式',
  `pay_status` varchar(32) NOT NULL COMMENT '支付状态',
  `pay_amount` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '支付金额',
  `third_party_trade_no` varchar(64) DEFAULT NULL COMMENT '第三方交易号',
  `pay_request_json` json DEFAULT NULL COMMENT '支付请求报文',
  `pay_response_json` json DEFAULT NULL COMMENT '支付响应报文',
  `paid_at` datetime DEFAULT NULL COMMENT '支付完成时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_pay_no_deleted` (`pay_no`, `deleted`),
  UNIQUE KEY `uk_third_party_trade_no_deleted` (`third_party_trade_no`, `deleted`),
  KEY `idx_order_id` (`order_id`),
  KEY `idx_pay_status` (`pay_status`),
  KEY `idx_paid_at` (`paid_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='支付流水表';

CREATE TABLE IF NOT EXISTS `cdd_order_refund_record` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `refund_no` varchar(32) NOT NULL COMMENT '退款单号',
  `order_id` bigint NOT NULL COMMENT '订单ID',
  `order_no` varchar(32) NOT NULL COMMENT '订单号',
  `pay_record_id` bigint DEFAULT NULL COMMENT '支付记录ID',
  `merchant_id` bigint NOT NULL COMMENT '商家ID',
  `store_id` bigint NOT NULL COMMENT '店铺ID',
  `refund_reason` varchar(256) DEFAULT NULL COMMENT '退款原因',
  `refund_status` varchar(32) NOT NULL COMMENT '退款状态',
  `refund_amount` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '退款金额',
  `third_party_refund_no` varchar(64) DEFAULT NULL COMMENT '第三方退款单号',
  `applied_at` datetime DEFAULT NULL COMMENT '申请时间',
  `success_at` datetime DEFAULT NULL COMMENT '退款成功时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_refund_no_deleted` (`refund_no`, `deleted`),
  UNIQUE KEY `uk_third_party_refund_no_deleted` (`third_party_refund_no`, `deleted`),
  KEY `idx_order_id` (`order_id`),
  KEY `idx_refund_status` (`refund_status`),
  KEY `idx_store_created_at` (`store_id`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='退款流水表';

CREATE TABLE IF NOT EXISTS `cdd_order_after_sale` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `after_sale_no` varchar(32) NOT NULL COMMENT '售后单号',
  `order_id` bigint NOT NULL COMMENT '订单ID',
  `order_item_id` bigint DEFAULT NULL COMMENT '订单项ID',
  `merchant_id` bigint NOT NULL COMMENT '商家ID',
  `store_id` bigint NOT NULL COMMENT '店铺ID',
  `user_id` bigint NOT NULL COMMENT '用户ID',
  `after_sale_type` varchar(32) NOT NULL COMMENT '售后类型',
  `after_sale_status` varchar(32) NOT NULL COMMENT '售后状态',
  `apply_reason` varchar(256) DEFAULT NULL COMMENT '申请原因',
  `apply_desc` varchar(512) DEFAULT NULL COMMENT '申请说明',
  `refund_amount` decimal(10,2) DEFAULT NULL COMMENT '退款金额',
  `handled_by` bigint DEFAULT NULL COMMENT '处理人',
  `handled_at` datetime DEFAULT NULL COMMENT '处理时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_after_sale_no_deleted` (`after_sale_no`, `deleted`),
  KEY `idx_order_id` (`order_id`),
  KEY `idx_store_status` (`store_id`, `after_sale_status`),
  KEY `idx_user_created_at` (`user_id`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='售后单表';

CREATE TABLE IF NOT EXISTS `cdd_order_status_log` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `order_id` bigint NOT NULL COMMENT '订单ID',
  `order_no` varchar(32) NOT NULL COMMENT '订单号',
  `from_status` varchar(32) DEFAULT NULL COMMENT '原状态',
  `to_status` varchar(32) NOT NULL COMMENT '新状态',
  `operate_type` varchar(32) NOT NULL COMMENT '操作类型',
  `operator_id` bigint DEFAULT NULL COMMENT '操作人ID',
  `operator_name` varchar(64) DEFAULT NULL COMMENT '操作人名称',
  `remark` varchar(512) DEFAULT NULL COMMENT '备注',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  KEY `idx_order_id` (`order_id`),
  KEY `idx_order_created_at` (`order_no`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单状态流转日志表';
