SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `cdd_order_pay_callback_record` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `pay_record_id` bigint DEFAULT NULL COMMENT '支付记录ID',
  `pay_no` varchar(32) NOT NULL COMMENT '支付单号',
  `merchant_id` bigint NOT NULL COMMENT '商家ID',
  `store_id` bigint DEFAULT NULL COMMENT '店铺ID',
  `pay_channel` varchar(32) NOT NULL COMMENT '支付渠道',
  `third_party_trade_no` varchar(64) DEFAULT NULL COMMENT '第三方交易号',
  `callback_event_id` varchar(64) NOT NULL COMMENT '回调事件ID',
  `callback_status` varchar(32) NOT NULL COMMENT '回调处理状态',
  `processed_result` varchar(32) DEFAULT NULL COMMENT '处理结果',
  `failure_reason` varchar(512) DEFAULT NULL COMMENT '失败原因',
  `callback_payload_json` json DEFAULT NULL COMMENT '回调报文',
  `processed_at` datetime DEFAULT NULL COMMENT '处理完成时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_pay_no_event_deleted` (`pay_no`, `callback_event_id`, `deleted`),
  UNIQUE KEY `uk_trade_no_deleted` (`third_party_trade_no`, `deleted`),
  KEY `idx_pay_record_id` (`pay_record_id`),
  KEY `idx_status_created` (`callback_status`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='支付回调幂等记录表';

CREATE TABLE IF NOT EXISTS `cdd_order_refund_callback_record` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `refund_record_id` bigint DEFAULT NULL COMMENT '退款记录ID',
  `refund_no` varchar(32) NOT NULL COMMENT '退款单号',
  `order_id` bigint DEFAULT NULL COMMENT '订单ID',
  `merchant_id` bigint NOT NULL COMMENT '商家ID',
  `store_id` bigint DEFAULT NULL COMMENT '店铺ID',
  `third_party_refund_no` varchar(64) DEFAULT NULL COMMENT '第三方退款单号',
  `callback_event_id` varchar(64) NOT NULL COMMENT '回调事件ID',
  `callback_status` varchar(32) NOT NULL COMMENT '回调处理状态',
  `processed_result` varchar(32) DEFAULT NULL COMMENT '处理结果',
  `failure_reason` varchar(512) DEFAULT NULL COMMENT '失败原因',
  `callback_payload_json` json DEFAULT NULL COMMENT '回调报文',
  `processed_at` datetime DEFAULT NULL COMMENT '处理完成时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_refund_no_event_deleted` (`refund_no`, `callback_event_id`, `deleted`),
  UNIQUE KEY `uk_third_party_refund_no_deleted` (`third_party_refund_no`, `deleted`),
  KEY `idx_refund_record_id` (`refund_record_id`),
  KEY `idx_status_created` (`callback_status`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='退款回调幂等记录表';

CREATE TABLE IF NOT EXISTS `cdd_release_callback_record` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `task_id` bigint NOT NULL COMMENT '发布任务ID',
  `task_no` varchar(32) NOT NULL COMMENT '发布任务号',
  `merchant_id` bigint NOT NULL COMMENT '商家ID',
  `store_id` bigint DEFAULT NULL COMMENT '店铺ID',
  `mini_program_id` bigint DEFAULT NULL COMMENT '小程序ID',
  `step_code` varchar(64) NOT NULL COMMENT '步骤编码',
  `source_system` varchar(32) NOT NULL COMMENT '来源系统',
  `callback_event_id` varchar(64) NOT NULL COMMENT '回调事件ID',
  `callback_status` varchar(32) NOT NULL COMMENT '回调处理状态',
  `processed_result` varchar(32) DEFAULT NULL COMMENT '处理结果',
  `failure_reason` varchar(512) DEFAULT NULL COMMENT '失败原因',
  `callback_payload_json` json DEFAULT NULL COMMENT '回调报文',
  `processed_at` datetime DEFAULT NULL COMMENT '处理完成时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_task_step_event_deleted` (`task_id`, `step_code`, `callback_event_id`, `deleted`),
  KEY `idx_task_step` (`task_id`, `step_code`),
  KEY `idx_status_created` (`callback_status`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='发布回调幂等记录表';

CREATE TABLE IF NOT EXISTS `cdd_compensation_task` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `task_code` varchar(64) NOT NULL COMMENT '补偿任务编码',
  `biz_type` varchar(64) NOT NULL COMMENT '业务类型',
  `biz_id` varchar(64) NOT NULL COMMENT '业务标识',
  `compensation_type` varchar(64) NOT NULL COMMENT '补偿类型',
  `task_status` varchar(32) NOT NULL COMMENT '任务状态',
  `retry_count` int NOT NULL DEFAULT '0' COMMENT '已重试次数',
  `max_retry_count` int NOT NULL DEFAULT '10' COMMENT '最大重试次数',
  `next_retry_at` datetime DEFAULT NULL COMMENT '下次重试时间',
  `last_error_code` varchar(64) DEFAULT NULL COMMENT '最后错误码',
  `last_error_message` varchar(512) DEFAULT NULL COMMENT '最后错误信息',
  `payload_json` json DEFAULT NULL COMMENT '补偿上下文',
  `resolved_at` datetime DEFAULT NULL COMMENT '解决时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_task_code_deleted` (`task_code`, `deleted`),
  UNIQUE KEY `uk_biz_comp_type_active_deleted` (`biz_type`, `biz_id`, `compensation_type`, `deleted`),
  KEY `idx_status_next_retry` (`task_status`, `next_retry_at`),
  KEY `idx_biz_type_id` (`biz_type`, `biz_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='通用补偿任务表';
