spring:
  application:
    name: cdd-auth-service
  profiles:
    active: ${CDD_ENV:local}

cdd:
  runtime:
    config-mode: ${CDD_CONFIG_MODE:nacos}
  nacos:
    server-addr: ${CDD_NACOS_SERVER_ADDR:http://127.0.0.1:${CDD_LOCAL_NACOS_PORT:8848}}
    group: ${CDD_NACOS_GROUP:CHENGDD}
  security:
    permit-all: true
    permit-paths:
      - /actuator/health
      - /actuator/info
      - /api/auth/platform/login
      - /api/auth/merchant/login
      - /api/auth/token/refresh
      - /api/auth/logout
    jwt:
      issuer: cdd-auth-service
      secret: chengdd-jwt-secret-change-me-20260321-123456
      access-token-ttl: 30m
      refresh-token-ttl: 7d

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
