spring:
  datasource:
    url: ${CDD_AUTH_DB_URL}
    username: ${CDD_AUTH_DB_USERNAME}
    password: ${CDD_AUTH_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

cdd:
  runtime:
    env: prod

server:
  port: 8081
