spring:
  datasource:
    url: ${CDD_ORDER_DB_URL:jdbc:h2:mem:cdd-order-local;MODE=MySQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;DB_CLOSE_DELAY=-1}
    username: ${CDD_ORDER_DB_USERNAME:sa}
    password: ${CDD_ORDER_DB_PASSWORD:}
    driver-class-name: ${CDD_ORDER_DB_DRIVER_CLASS_NAME:org.h2.Driver}
  sql:
    init:
      mode: ${CDD_ORDER_SQL_INIT_MODE:always}
      schema-locations: ${CDD_ORDER_SQL_SCHEMA_LOCATIONS:classpath:db/order/h2/schema.sql}
      data-locations: ${CDD_ORDER_SQL_DATA_LOCATIONS:classpath:db/order/h2/data-local.sql}

cdd:
  runtime:
    env: local

server:
  port: 8085
