spring:
  application:
    name: cdd-merchant-service
  profiles:
    active: ${CDD_ENV:local}

cdd:
  runtime:
    config-mode: ${CDD_CONFIG_MODE:nacos}
  nacos:
    server-addr: ${CDD_NACOS_SERVER_ADDR:http://127.0.0.1:${CDD_LOCAL_NACOS_PORT:8848}}
    group: ${CDD_NACOS_GROUP:CHENGDD}

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
