spring:
  application:
    name: cdd-product-service
  profiles:
    active: ${CDD_ENV:local},${CDD_CONFIG_MODE:nacos}
  cloud:
    nacos:
      config:
        enabled: false
        import-check:
          enabled: false
      discovery:
        enabled: false

cdd:
  runtime:
    env: ${CDD_ENV:local}
    config-mode: ${CDD_CONFIG_MODE:nacos}

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
