SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- 程哒哒数据库结构草案
-- 适用范围：MySQL 5.7 / InnoDB / utf8mb4
-- 说明：
-- 1. 主键统一为 bigint，应用侧发号，数据库不使用自增主键。
-- 2. 当前仅输出逻辑外键，不创建 FK 约束，便于低成本交付与后续拆库。
-- 3. 统一保留 deleted、version、created_at、updated_at 字段。

CREATE TABLE IF NOT EXISTS `cdd_merchant_application` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `merchant_name` varchar(128) NOT NULL COMMENT '商家主体名称',
  `merchant_type` varchar(32) NOT NULL COMMENT '商家类型：enterprise/individual',
  `contact_name` varchar(64) NOT NULL COMMENT '联系人',
  `contact_mobile` varchar(32) NOT NULL COMMENT '联系电话',
  `legal_person_name` varchar(64) DEFAULT NULL COMMENT '法人姓名',
  `business_category` varchar(64) DEFAULT NULL COMMENT '经营类目',
  `brand_name` varchar(128) DEFAULT NULL COMMENT '品牌名称',
  `license_file_url` varchar(512) DEFAULT NULL COMMENT '营业执照地址',
  `status` varchar(32) NOT NULL COMMENT '申请状态',
  `reject_reason` varchar(512) DEFAULT NULL COMMENT '驳回原因',
  `submitted_at` datetime DEFAULT NULL COMMENT '提交时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_contact_mobile_deleted` (`contact_mobile`, `deleted`),
  KEY `idx_status_submitted_at` (`status`, `submitted_at`),
  KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商家入驻申请表';

CREATE TABLE IF NOT EXISTS `cdd_merchant_profile` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `merchant_no` varchar(32) NOT NULL COMMENT '商家编号',
  `merchant_name` varchar(128) NOT NULL COMMENT '商家名称',
  `merchant_type` varchar(32) NOT NULL COMMENT '商家类型',
  `brand_name` varchar(128) DEFAULT NULL COMMENT '品牌名称',
  `status` varchar(32) NOT NULL COMMENT '商家状态',
  `current_application_id` bigint DEFAULT NULL COMMENT '当前申请ID',
  `contact_name` varchar(64) NOT NULL COMMENT '联系人',
  `contact_mobile` varchar(32) NOT NULL COMMENT '联系电话',
  `business_scope` varchar(512) DEFAULT NULL COMMENT '经营范围',
  `settled_at` datetime DEFAULT NULL COMMENT '入驻时间',
  `remark` varchar(512) DEFAULT NULL COMMENT '备注',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_merchant_no_deleted` (`merchant_no`, `deleted`),
  UNIQUE KEY `uk_merchant_name_deleted` (`merchant_name`, `deleted`),
  KEY `idx_status` (`status`),
  KEY `idx_contact_mobile` (`contact_mobile`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商家主体资料表';

CREATE TABLE IF NOT EXISTS `cdd_merchant_store` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `merchant_id` bigint NOT NULL COMMENT '商家ID',
  `store_no` varchar(32) NOT NULL COMMENT '店铺编号',
  `store_name` varchar(128) NOT NULL COMMENT '店铺名称',
  `logo_url` varchar(512) DEFAULT NULL COMMENT '店铺Logo',
  `description` varchar(1024) DEFAULT NULL COMMENT '店铺简介',
  `business_status` varchar(32) NOT NULL COMMENT '营业状态',
  `shipping_sla_hours` int DEFAULT NULL COMMENT '履约时效小时数',
  `customer_service_type` varchar(32) DEFAULT NULL COMMENT '客服类型',
  `customer_service_value` varchar(128) DEFAULT NULL COMMENT '客服值',
  `return_address` varchar(512) DEFAULT NULL COMMENT '退货地址',
  `service_commitment` varchar(1024) DEFAULT NULL COMMENT '服务承诺',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_store_no_deleted` (`store_no`, `deleted`),
  UNIQUE KEY `uk_merchant_store_name_deleted` (`merchant_id`, `store_name`, `deleted`),
  KEY `idx_merchant_id` (`merchant_id`),
  KEY `idx_merchant_status` (`merchant_id`, `business_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商家店铺表';

CREATE TABLE IF NOT EXISTS `cdd_merchant_mini_program` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `merchant_id` bigint NOT NULL COMMENT '商家ID',
  `store_id` bigint NOT NULL COMMENT '店铺ID',
  `app_id` varchar(64) NOT NULL COMMENT '小程序AppID',
  `app_secret_masked` varchar(128) DEFAULT NULL COMMENT '脱敏后的AppSecret',
  `payment_mch_id` varchar(64) DEFAULT NULL COMMENT '支付商户号',
  `server_domain` varchar(256) DEFAULT NULL COMMENT '服务域名',
  `binding_status` varchar(32) NOT NULL COMMENT '绑定状态',
  `current_template_version` varchar(64) DEFAULT NULL COMMENT '当前模板版本',
  `last_detect_result_json` json DEFAULT NULL COMMENT '最近检测结果',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_app_id_deleted` (`app_id`, `deleted`),
  KEY `idx_merchant_store` (`merchant_id`, `store_id`),
  KEY `idx_binding_status` (`binding_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商家小程序接入配置表';

CREATE TABLE IF NOT EXISTS `cdd_merchant_sub_account` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `merchant_id` bigint NOT NULL COMMENT '商家ID',
  `account_name` varchar(64) NOT NULL COMMENT '登录账号',
  `display_name` varchar(64) NOT NULL COMMENT '显示名称',
  `mobile` varchar(32) DEFAULT NULL COMMENT '手机号',
  `status` varchar(32) NOT NULL COMMENT '账号状态',
  `role_label` varchar(64) DEFAULT NULL COMMENT '角色标签',
  `password_hash` varchar(256) DEFAULT NULL COMMENT '密码哈希',
  `last_login_at` datetime DEFAULT NULL COMMENT '最后登录时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_account_name_deleted` (`account_name`, `deleted`),
  UNIQUE KEY `uk_mobile_deleted` (`mobile`, `deleted`),
  KEY `idx_merchant_id` (`merchant_id`),
  KEY `idx_merchant_status` (`merchant_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商家子账号表';

CREATE TABLE IF NOT EXISTS `cdd_merchant_account_scope` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `merchant_id` bigint NOT NULL COMMENT '商家ID',
  `account_id` bigint NOT NULL COMMENT '账号ID',
  `scope_type` varchar(32) NOT NULL COMMENT '范围类型',
  `scope_object_type` varchar(32) NOT NULL COMMENT '对象类型',
  `scope_object_id` bigint NOT NULL COMMENT '对象ID',
  `action_permissions_json` json DEFAULT NULL COMMENT '动作权限集合',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  KEY `idx_account_id` (`account_id`),
  KEY `idx_scope_object` (`scope_object_type`, `scope_object_id`),
  KEY `idx_account_scope` (`account_id`, `scope_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商家子账号数据范围表';

CREATE TABLE IF NOT EXISTS `cdd_decoration_home_config` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `merchant_id` bigint NOT NULL COMMENT '商家ID',
  `store_id` bigint NOT NULL COMMENT '店铺ID',
  `mini_program_id` bigint NOT NULL COMMENT '小程序ID',
  `home_template_code` varchar(64) NOT NULL COMMENT '首页模板编码',
  `home_style_mode` varchar(32) DEFAULT NULL COMMENT '首页风格模式',
  `theme_color` varchar(32) DEFAULT NULL COMMENT '主题色',
  `search_placeholder` varchar(128) DEFAULT NULL COMMENT '搜索占位文案',
  `header_service_bar_json` json DEFAULT NULL COMMENT '顶部服务条',
  `brand_hero_block_json` json DEFAULT NULL COMMENT '头图配置',
  `delivery_promise_text` varchar(128) DEFAULT NULL COMMENT '配送承诺文案',
  `delivery_fee_text` varchar(64) DEFAULT NULL COMMENT '配送费文案',
  `minimum_order_text` varchar(64) DEFAULT NULL COMMENT '起送价文案',
  `announcement_text` varchar(512) DEFAULT NULL COMMENT '公告文案',
  `status` varchar(32) NOT NULL COMMENT '配置状态',
  `version_no` int NOT NULL DEFAULT '1' COMMENT '版本号',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_store_mini_program_deleted` (`store_id`, `mini_program_id`, `deleted`),
  KEY `idx_merchant_store` (`merchant_id`, `store_id`),
  KEY `idx_status_version` (`status`, `version_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='首页装修主配置表';

CREATE TABLE IF NOT EXISTS `cdd_decoration_home_module` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `merchant_id` bigint NOT NULL COMMENT '商家ID',
  `store_id` bigint NOT NULL COMMENT '店铺ID',
  `home_config_id` bigint NOT NULL COMMENT '首页配置ID',
  `module_type` varchar(64) NOT NULL COMMENT '模块类型',
  `module_name` varchar(128) NOT NULL COMMENT '模块名称',
  `sort_order` int NOT NULL DEFAULT '0' COMMENT '排序号',
  `is_enabled` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否启用',
  `style_mode` varchar(32) DEFAULT NULL COMMENT '模块风格',
  `data_source_type` varchar(32) DEFAULT NULL COMMENT '数据源类型',
  `data_source_id` bigint DEFAULT NULL COMMENT '数据源ID',
  `jump_target_json` json DEFAULT NULL COMMENT '跳转配置',
  `config_payload_json` json DEFAULT NULL COMMENT '模块配置',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  KEY `idx_home_config_sort` (`home_config_id`, `sort_order`),
  KEY `idx_home_config_enabled` (`home_config_id`, `is_enabled`),
  KEY `idx_module_type` (`module_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='首页装修模块表';

CREATE TABLE IF NOT EXISTS `cdd_decoration_home_version` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `merchant_id` bigint NOT NULL COMMENT '商家ID',
  `store_id` bigint NOT NULL COMMENT '店铺ID',
  `home_config_id` bigint NOT NULL COMMENT '首页配置ID',
  `version_no` int NOT NULL COMMENT '版本号',
  `version_status` varchar(32) NOT NULL COMMENT '版本状态',
  `snapshot_json` json NOT NULL COMMENT '配置快照',
  `published_at` datetime DEFAULT NULL COMMENT '发布时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  KEY `idx_home_config_version` (`home_config_id`, `version_no`),
  KEY `idx_home_config_status` (`home_config_id`, `version_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='首页装修版本记录表';

CREATE TABLE IF NOT EXISTS `cdd_decoration_template_binding` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `merchant_id` bigint NOT NULL COMMENT '商家ID',
  `store_id` bigint NOT NULL COMMENT '店铺ID',
  `mini_program_id` bigint NOT NULL COMMENT '小程序ID',
  `template_code` varchar(64) NOT NULL COMMENT '模板编码',
  `style_mode` varchar(32) DEFAULT NULL COMMENT '风格模式',
  `binding_status` varchar(32) NOT NULL COMMENT '绑定状态',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_store_template_deleted` (`store_id`, `mini_program_id`, `template_code`, `deleted`),
  KEY `idx_merchant_store` (`merchant_id`, `store_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='首页模板绑定表';

CREATE TABLE IF NOT EXISTS `cdd_product_category_template` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `template_name` varchar(128) NOT NULL COMMENT '模板名称',
  `industry_code` varchar(64) NOT NULL COMMENT '行业编码',
  `template_version` varchar(32) NOT NULL COMMENT '模板版本',
  `max_level` int NOT NULL DEFAULT '3' COMMENT '最大层级',
  `status` varchar(32) NOT NULL COMMENT '模板状态',
  `default_sort_rule` varchar(64) DEFAULT NULL COMMENT '默认排序规则',
  `template_desc` varchar(512) DEFAULT NULL COMMENT '模板说明',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_template_name_version_deleted` (`template_name`, `template_version`, `deleted`),
  KEY `idx_industry_status` (`industry_code`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='平台分类模板表';

CREATE TABLE IF NOT EXISTS `cdd_product_category_template_attribute` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `template_id` bigint NOT NULL COMMENT '模板ID',
  `attribute_code` varchar(64) NOT NULL COMMENT '属性编码',
  `attribute_name` varchar(128) NOT NULL COMMENT '属性名称',
  `value_type` varchar(32) NOT NULL COMMENT '值类型',
  `is_required` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否必填',
  `is_sale_attribute` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否销售属性',
  `option_values_json` json DEFAULT NULL COMMENT '候选值',
  `sort_order` int NOT NULL DEFAULT '0' COMMENT '排序号',
  `status` varchar(32) NOT NULL COMMENT '状态',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_template_attr_code_deleted` (`template_id`, `attribute_code`, `deleted`),
  KEY `idx_template_sort` (`template_id`, `sort_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='分类模板属性表';

CREATE TABLE IF NOT EXISTS `cdd_product_category` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `merchant_id` bigint NOT NULL COMMENT '商家ID',
  `store_id` bigint DEFAULT NULL COMMENT '店铺ID',
  `template_id` bigint DEFAULT NULL COMMENT '来源模板ID',
  `parent_id` bigint NOT NULL DEFAULT '0' COMMENT '父分类ID',
  `category_name` varchar(128) NOT NULL COMMENT '分类名称',
  `category_icon_url` varchar(512) DEFAULT NULL COMMENT '分类图标',
  `category_level` int NOT NULL DEFAULT '1' COMMENT '分类层级',
  `sort_order` int NOT NULL DEFAULT '0' COMMENT '排序号',
  `is_enabled` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否启用',
  `is_visible` tinyint(1) NOT NULL DEFAULT '1' COMMENT '前台是否可见',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_merchant_parent_name_deleted` (`merchant_id`, `parent_id`, `category_name`, `deleted`),
  KEY `idx_merchant_parent` (`merchant_id`, `parent_id`),
  KEY `idx_merchant_enabled` (`merchant_id`, `is_enabled`),
  KEY `idx_merchant_visible` (`merchant_id`, `is_visible`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商家分类表';

CREATE TABLE IF NOT EXISTS `cdd_product_category_attribute` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `category_id` bigint NOT NULL COMMENT '分类ID',
  `attribute_code` varchar(64) NOT NULL COMMENT '属性编码',
  `attribute_name` varchar(128) NOT NULL COMMENT '属性名称',
  `value_type` varchar(32) NOT NULL COMMENT '值类型',
  `is_required` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否必填',
  `is_sale_attribute` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否销售属性',
  `option_values_json` json DEFAULT NULL COMMENT '候选值',
  `sort_order` int NOT NULL DEFAULT '0' COMMENT '排序号',
  `status` varchar(32) NOT NULL COMMENT '状态',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_category_attr_code_deleted` (`category_id`, `attribute_code`, `deleted`),
  KEY `idx_category_sort` (`category_id`, `sort_order`),
  KEY `idx_category_status` (`category_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商家分类属性表';

CREATE TABLE IF NOT EXISTS `cdd_product_spu` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `merchant_id` bigint NOT NULL COMMENT '商家ID',
  `store_id` bigint NOT NULL COMMENT '店铺ID',
  `category_id` bigint NOT NULL COMMENT '分类ID',
  `product_name` varchar(256) NOT NULL COMMENT '商品名称',
  `product_sub_title` varchar(256) DEFAULT NULL COMMENT '副标题',
  `main_image_url` varchar(512) DEFAULT NULL COMMENT '主图',
  `media_gallery_json` json DEFAULT NULL COMMENT '图文素材',
  `product_desc` text COMMENT '商品描述',
  `status` varchar(32) NOT NULL COMMENT '商品状态',
  `publish_check_status` varchar(32) NOT NULL COMMENT '发布检查状态',
  `sale_label_json` json DEFAULT NULL COMMENT '卖点标签',
  `delivery_type` varchar(32) DEFAULT NULL COMMENT '配送类型',
  `sort_order` int NOT NULL DEFAULT '0' COMMENT '排序号',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_store_product_name_deleted` (`store_id`, `product_name`, `deleted`),
  KEY `idx_store_category_status` (`store_id`, `category_id`, `status`),
  KEY `idx_store_publish_status` (`store_id`, `publish_check_status`),
  KEY `idx_merchant_created_at` (`merchant_id`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商品SPU表';

CREATE TABLE IF NOT EXISTS `cdd_product_sku` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `merchant_id` bigint NOT NULL COMMENT '商家ID',
  `store_id` bigint NOT NULL COMMENT '店铺ID',
  `product_id` bigint NOT NULL COMMENT '商品ID',
  `sku_code` varchar(64) NOT NULL COMMENT 'SKU编码',
  `sku_name` varchar(256) NOT NULL COMMENT 'SKU名称',
  `spec_json` json DEFAULT NULL COMMENT '规格组合',
  `sale_price` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '销售价',
  `market_price` decimal(10,2) DEFAULT NULL COMMENT '划线价',
  `cost_price` decimal(10,2) DEFAULT NULL COMMENT '成本价',
  `weight_gram` int DEFAULT NULL COMMENT '重量克',
  `volume_json` json DEFAULT NULL COMMENT '体积信息',
  `status` varchar(32) NOT NULL COMMENT 'SKU状态',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sku_code_deleted` (`sku_code`, `deleted`),
  KEY `idx_product_id` (`product_id`),
  KEY `idx_product_status` (`product_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商品SKU表';

CREATE TABLE IF NOT EXISTS `cdd_product_stock` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `merchant_id` bigint NOT NULL COMMENT '商家ID',
  `store_id` bigint NOT NULL COMMENT '店铺ID',
  `product_id` bigint NOT NULL COMMENT '商品ID',
  `sku_id` bigint NOT NULL COMMENT 'SKU ID',
  `available_stock` int NOT NULL DEFAULT '0' COMMENT '可售库存',
  `locked_stock` int NOT NULL DEFAULT '0' COMMENT '锁定库存',
  `warning_stock` int DEFAULT NULL COMMENT '预警库存',
  `stock_status` varchar(32) NOT NULL COMMENT '库存状态',
  `last_stock_in_at` datetime DEFAULT NULL COMMENT '最近入库时间',
  `last_stock_out_at` datetime DEFAULT NULL COMMENT '最近出库时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sku_id_deleted` (`sku_id`, `deleted`),
  KEY `idx_product_id` (`product_id`),
  KEY `idx_merchant_sku` (`merchant_id`, `sku_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商品库存表';

CREATE TABLE IF NOT EXISTS `cdd_product_publish_record` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `merchant_id` bigint NOT NULL COMMENT '商家ID',
  `store_id` bigint NOT NULL COMMENT '店铺ID',
  `product_id` bigint NOT NULL COMMENT '商品ID',
  `mini_program_id` bigint DEFAULT NULL COMMENT '小程序ID',
  `publish_result` varchar(32) NOT NULL COMMENT '发布结果',
  `publish_message` varchar(512) DEFAULT NULL COMMENT '发布信息',
  `published_at` datetime DEFAULT NULL COMMENT '发布时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  KEY `idx_product_created_at` (`product_id`, `created_at`),
  KEY `idx_store_result` (`store_id`, `publish_result`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商品发布记录表';

CREATE TABLE IF NOT EXISTS `cdd_product_attribute_snapshot` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `product_id` bigint NOT NULL COMMENT '商品ID',
  `attribute_id` bigint NOT NULL COMMENT '属性ID',
  `attribute_code` varchar(64) NOT NULL COMMENT '属性编码',
  `attribute_name` varchar(128) NOT NULL COMMENT '属性名称',
  `attribute_value_json` json DEFAULT NULL COMMENT '属性值快照',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  KEY `idx_product_id` (`product_id`),
  KEY `idx_product_attribute` (`product_id`, `attribute_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商品属性快照表';

CREATE TABLE IF NOT EXISTS `cdd_order_cart_item` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `merchant_id` bigint NOT NULL COMMENT '商家ID',
  `store_id` bigint NOT NULL COMMENT '店铺ID',
  `user_id` bigint NOT NULL COMMENT '用户ID',
  `product_id` bigint NOT NULL COMMENT '商品ID',
  `sku_id` bigint NOT NULL COMMENT 'SKU ID',
  `quantity` int NOT NULL DEFAULT '1' COMMENT '购买数量',
  `selected` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否选中',
  `snapshot_price` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '加入时价格快照',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_store_sku_deleted` (`user_id`, `store_id`, `sku_id`, `deleted`),
  KEY `idx_user_store_selected` (`user_id`, `store_id`, `selected`),
  KEY `idx_merchant_user` (`merchant_id`, `user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='购物车明细表';

CREATE TABLE IF NOT EXISTS `cdd_order_checkout_snapshot` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `merchant_id` bigint NOT NULL COMMENT '商家ID',
  `store_id` bigint NOT NULL COMMENT '店铺ID',
  `user_id` bigint NOT NULL COMMENT '用户ID',
  `snapshot_token` varchar(64) NOT NULL COMMENT '结算快照令牌',
  `cart_item_ids_json` json DEFAULT NULL COMMENT '购物车项ID列表',
  `pricing_snapshot_json` json NOT NULL COMMENT '试算快照',
  `address_snapshot_json` json DEFAULT NULL COMMENT '地址快照',
  `coupon_snapshot_json` json DEFAULT NULL COMMENT '优惠快照',
  `expired_at` datetime NOT NULL COMMENT '过期时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_snapshot_token_deleted` (`snapshot_token`, `deleted`),
  KEY `idx_user_expired` (`user_id`, `expired_at`),
  KEY `idx_store_created_at` (`store_id`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='结算快照表';

CREATE TABLE IF NOT EXISTS `cdd_order_info` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `order_no` varchar(32) NOT NULL COMMENT '订单号',
  `merchant_id` bigint NOT NULL COMMENT '商家ID',
  `store_id` bigint NOT NULL COMMENT '店铺ID',
  `user_id` bigint NOT NULL COMMENT '用户ID',
  `checkout_snapshot_id` bigint DEFAULT NULL COMMENT '结算快照ID',
  `order_status` varchar(32) NOT NULL COMMENT '订单状态',
  `pay_status` varchar(32) NOT NULL COMMENT '支付状态',
  `delivery_status` varchar(32) DEFAULT NULL COMMENT '履约状态',
  `buyer_remark` varchar(512) DEFAULT NULL COMMENT '买家备注',
  `total_amount` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '订单总金额',
  `discount_amount` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '优惠金额',
  `payable_amount` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '应付金额',
  `paid_amount` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '实付金额',
  `delivery_fee_amount` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '配送费',
  `receiver_name` varchar(64) DEFAULT NULL COMMENT '收货人',
  `receiver_mobile` varchar(32) DEFAULT NULL COMMENT '收货手机号',
  `receiver_address` varchar(512) DEFAULT NULL COMMENT '收货地址',
  `paid_at` datetime DEFAULT NULL COMMENT '支付时间',
  `cancelled_at` datetime DEFAULT NULL COMMENT '取消时间',
  `finished_at` datetime DEFAULT NULL COMMENT '完成时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_order_no_deleted` (`order_no`, `deleted`),
  KEY `idx_user_created_at` (`user_id`, `created_at`),
  KEY `idx_store_status_created` (`store_id`, `order_status`, `created_at`),
  KEY `idx_merchant_pay_status` (`merchant_id`, `pay_status`),
  KEY `idx_store_pay_status` (`store_id`, `pay_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单主表';

CREATE TABLE IF NOT EXISTS `cdd_order_item` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `order_id` bigint NOT NULL COMMENT '订单ID',
  `merchant_id` bigint NOT NULL COMMENT '商家ID',
  `store_id` bigint NOT NULL COMMENT '店铺ID',
  `product_id` bigint NOT NULL COMMENT '商品ID',
  `sku_id` bigint NOT NULL COMMENT 'SKU ID',
  `product_name` varchar(256) NOT NULL COMMENT '商品名称快照',
  `sku_name` varchar(256) NOT NULL COMMENT 'SKU名称快照',
  `sku_spec_json` json DEFAULT NULL COMMENT 'SKU规格快照',
  `sale_price` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '成交单价',
  `quantity` int NOT NULL DEFAULT '1' COMMENT '购买数量',
  `line_amount` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '行金额',
  `refund_status` varchar(32) DEFAULT NULL COMMENT '退款状态',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  KEY `idx_order_id` (`order_id`),
  KEY `idx_product_id` (`product_id`),
  KEY `idx_sku_id` (`sku_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单商品明细表';

CREATE TABLE IF NOT EXISTS `cdd_order_pay_record` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `pay_no` varchar(32) NOT NULL COMMENT '支付单号',
  `order_id` bigint NOT NULL COMMENT '订单ID',
  `order_no` varchar(32) NOT NULL COMMENT '订单号',
  `merchant_id` bigint NOT NULL COMMENT '商家ID',
  `store_id` bigint NOT NULL COMMENT '店铺ID',
  `pay_channel` varchar(32) NOT NULL COMMENT '支付渠道',
  `pay_method` varchar(32) DEFAULT NULL COMMENT '支付方式',
  `pay_status` varchar(32) NOT NULL COMMENT '支付状态',
  `pay_amount` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '支付金额',
  `third_party_trade_no` varchar(64) DEFAULT NULL COMMENT '第三方交易号',
  `pay_request_json` json DEFAULT NULL COMMENT '支付请求报文',
  `pay_response_json` json DEFAULT NULL COMMENT '支付响应报文',
  `paid_at` datetime DEFAULT NULL COMMENT '支付完成时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_pay_no_deleted` (`pay_no`, `deleted`),
  UNIQUE KEY `uk_third_party_trade_no_deleted` (`third_party_trade_no`, `deleted`),
  KEY `idx_order_id` (`order_id`),
  KEY `idx_pay_status` (`pay_status`),
  KEY `idx_paid_at` (`paid_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='支付流水表';

CREATE TABLE IF NOT EXISTS `cdd_order_refund_record` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `refund_no` varchar(32) NOT NULL COMMENT '退款单号',
  `order_id` bigint NOT NULL COMMENT '订单ID',
  `order_no` varchar(32) NOT NULL COMMENT '订单号',
  `pay_record_id` bigint DEFAULT NULL COMMENT '支付记录ID',
  `merchant_id` bigint NOT NULL COMMENT '商家ID',
  `store_id` bigint NOT NULL COMMENT '店铺ID',
  `refund_reason` varchar(256) DEFAULT NULL COMMENT '退款原因',
  `refund_status` varchar(32) NOT NULL COMMENT '退款状态',
  `refund_amount` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '退款金额',
  `third_party_refund_no` varchar(64) DEFAULT NULL COMMENT '第三方退款单号',
  `applied_at` datetime DEFAULT NULL COMMENT '申请时间',
  `success_at` datetime DEFAULT NULL COMMENT '退款成功时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_refund_no_deleted` (`refund_no`, `deleted`),
  KEY `idx_order_id` (`order_id`),
  KEY `idx_refund_status` (`refund_status`),
  KEY `idx_store_created_at` (`store_id`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='退款流水表';

CREATE TABLE IF NOT EXISTS `cdd_order_after_sale` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `after_sale_no` varchar(32) NOT NULL COMMENT '售后单号',
  `order_id` bigint NOT NULL COMMENT '订单ID',
  `order_item_id` bigint DEFAULT NULL COMMENT '订单项ID',
  `merchant_id` bigint NOT NULL COMMENT '商家ID',
  `store_id` bigint NOT NULL COMMENT '店铺ID',
  `user_id` bigint NOT NULL COMMENT '用户ID',
  `after_sale_type` varchar(32) NOT NULL COMMENT '售后类型',
  `after_sale_status` varchar(32) NOT NULL COMMENT '售后状态',
  `apply_reason` varchar(256) DEFAULT NULL COMMENT '申请原因',
  `apply_desc` varchar(512) DEFAULT NULL COMMENT '申请说明',
  `refund_amount` decimal(10,2) DEFAULT NULL COMMENT '退款金额',
  `handled_by` bigint DEFAULT NULL COMMENT '处理人',
  `handled_at` datetime DEFAULT NULL COMMENT '处理时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_after_sale_no_deleted` (`after_sale_no`, `deleted`),
  KEY `idx_order_id` (`order_id`),
  KEY `idx_store_status` (`store_id`, `after_sale_status`),
  KEY `idx_user_created_at` (`user_id`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='售后单表';

CREATE TABLE IF NOT EXISTS `cdd_order_status_log` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `order_id` bigint NOT NULL COMMENT '订单ID',
  `order_no` varchar(32) NOT NULL COMMENT '订单号',
  `from_status` varchar(32) DEFAULT NULL COMMENT '原状态',
  `to_status` varchar(32) NOT NULL COMMENT '新状态',
  `operate_type` varchar(32) NOT NULL COMMENT '操作类型',
  `operator_id` bigint DEFAULT NULL COMMENT '操作人ID',
  `operator_name` varchar(64) DEFAULT NULL COMMENT '操作人名称',
  `remark` varchar(512) DEFAULT NULL COMMENT '备注',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  KEY `idx_order_id` (`order_id`),
  KEY `idx_order_created_at` (`order_no`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单状态流转日志表';

CREATE TABLE IF NOT EXISTS `cdd_template_version` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `template_code` varchar(64) NOT NULL COMMENT '模板编码',
  `template_name` varchar(128) NOT NULL COMMENT '模板名称',
  `template_version` varchar(32) NOT NULL COMMENT '模板版本',
  `template_type` varchar(32) NOT NULL COMMENT '模板类型',
  `runtime_package_url` varchar(512) DEFAULT NULL COMMENT '运行包地址',
  `source_package_url` varchar(512) DEFAULT NULL COMMENT '源码包地址',
  `change_summary` varchar(1024) DEFAULT NULL COMMENT '变更摘要',
  `status` varchar(32) NOT NULL COMMENT '模板状态',
  `released_at` datetime DEFAULT NULL COMMENT '模板发布时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_template_version_deleted` (`template_code`, `template_version`, `deleted`),
  KEY `idx_template_status` (`template_code`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='模板版本表';

CREATE TABLE IF NOT EXISTS `cdd_template_change_log` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `template_version_id` bigint NOT NULL COMMENT '模板版本ID',
  `change_type` varchar(32) NOT NULL COMMENT '变更类型',
  `change_summary` varchar(512) NOT NULL COMMENT '变更摘要',
  `change_detail` text COMMENT '变更详情',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  KEY `idx_template_version_id` (`template_version_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='模板变更记录表';

CREATE TABLE IF NOT EXISTS `cdd_release_task` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `task_no` varchar(32) NOT NULL COMMENT '发布任务号',
  `merchant_id` bigint NOT NULL COMMENT '商家ID',
  `store_id` bigint NOT NULL COMMENT '店铺ID',
  `mini_program_id` bigint NOT NULL COMMENT '小程序ID',
  `template_version_id` bigint NOT NULL COMMENT '模板版本ID',
  `release_type` varchar(32) NOT NULL COMMENT '发布类型',
  `release_status` varchar(32) NOT NULL COMMENT '发布状态',
  `trigger_source` varchar(32) NOT NULL COMMENT '触发来源',
  `release_snapshot_json` json DEFAULT NULL COMMENT '发布快照',
  `started_at` datetime DEFAULT NULL COMMENT '开始时间',
  `finished_at` datetime DEFAULT NULL COMMENT '结束时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_task_no_deleted` (`task_no`, `deleted`),
  KEY `idx_merchant_status` (`merchant_id`, `release_status`),
  KEY `idx_store_created_at` (`store_id`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='发布任务主表';

CREATE TABLE IF NOT EXISTS `cdd_release_task_detail` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `task_id` bigint NOT NULL COMMENT '任务ID',
  `step_code` varchar(64) NOT NULL COMMENT '步骤编码',
  `step_name` varchar(128) NOT NULL COMMENT '步骤名称',
  `step_status` varchar(32) NOT NULL COMMENT '步骤状态',
  `step_order` int NOT NULL DEFAULT '0' COMMENT '步骤顺序',
  `result_message` varchar(512) DEFAULT NULL COMMENT '执行结果',
  `started_at` datetime DEFAULT NULL COMMENT '开始时间',
  `finished_at` datetime DEFAULT NULL COMMENT '结束时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  KEY `idx_task_step_order` (`task_id`, `step_order`),
  KEY `idx_task_step_status` (`task_id`, `step_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='发布任务步骤表';

CREATE TABLE IF NOT EXISTS `cdd_release_gray_record` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `task_id` bigint NOT NULL COMMENT '任务ID',
  `gray_version` varchar(32) NOT NULL COMMENT '灰度版本',
  `gray_scope_json` json DEFAULT NULL COMMENT '灰度范围',
  `gray_status` varchar(32) NOT NULL COMMENT '灰度状态',
  `started_at` datetime DEFAULT NULL COMMENT '开始时间',
  `ended_at` datetime DEFAULT NULL COMMENT '结束时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  KEY `idx_task_id` (`task_id`),
  KEY `idx_gray_status` (`gray_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='灰度发布记录表';

CREATE TABLE IF NOT EXISTS `cdd_release_rollback_record` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `task_id` bigint NOT NULL COMMENT '任务ID',
  `rollback_target_version` varchar(32) NOT NULL COMMENT '回滚目标版本',
  `rollback_reason` varchar(512) DEFAULT NULL COMMENT '回滚原因',
  `rollback_status` varchar(32) NOT NULL COMMENT '回滚状态',
  `rolled_back_at` datetime DEFAULT NULL COMMENT '回滚时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  KEY `idx_task_id` (`task_id`),
  KEY `idx_rollback_status` (`rollback_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='回滚记录表';

CREATE TABLE IF NOT EXISTS `cdd_release_log` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `task_id` bigint NOT NULL COMMENT '任务ID',
  `log_level` varchar(16) NOT NULL COMMENT '日志级别',
  `log_stage` varchar(64) DEFAULT NULL COMMENT '日志阶段',
  `log_content` text COMMENT '日志内容',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  KEY `idx_task_created_at` (`task_id`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='发布日志表';

CREATE TABLE IF NOT EXISTS `cdd_marketing_coupon` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `merchant_id` bigint NOT NULL COMMENT '商家ID',
  `store_id` bigint NOT NULL COMMENT '店铺ID',
  `coupon_name` varchar(128) NOT NULL COMMENT '优惠券名称',
  `coupon_type` varchar(32) NOT NULL COMMENT '优惠券类型',
  `threshold_amount` decimal(10,2) DEFAULT NULL COMMENT '使用门槛',
  `discount_amount` decimal(10,2) DEFAULT NULL COMMENT '减免金额',
  `discount_rate` decimal(5,2) DEFAULT NULL COMMENT '折扣率',
  `issue_start_at` datetime DEFAULT NULL COMMENT '发放开始时间',
  `issue_end_at` datetime DEFAULT NULL COMMENT '发放结束时间',
  `status` varchar(32) NOT NULL COMMENT '状态',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  KEY `idx_store_status` (`store_id`, `status`),
  KEY `idx_issue_end_at` (`issue_end_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='优惠券定义表';

CREATE TABLE IF NOT EXISTS `cdd_marketing_coupon_record` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `coupon_id` bigint NOT NULL COMMENT '优惠券ID',
  `merchant_id` bigint NOT NULL COMMENT '商家ID',
  `store_id` bigint NOT NULL COMMENT '店铺ID',
  `user_id` bigint NOT NULL COMMENT '用户ID',
  `record_status` varchar(32) NOT NULL COMMENT '记录状态',
  `received_at` datetime DEFAULT NULL COMMENT '领取时间',
  `used_at` datetime DEFAULT NULL COMMENT '使用时间',
  `order_id` bigint DEFAULT NULL COMMENT '订单ID',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  KEY `idx_coupon_user` (`coupon_id`, `user_id`),
  KEY `idx_store_status` (`store_id`, `record_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户领券记录表';

CREATE TABLE IF NOT EXISTS `cdd_marketing_activity` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `merchant_id` bigint NOT NULL COMMENT '商家ID',
  `store_id` bigint NOT NULL COMMENT '店铺ID',
  `activity_name` varchar(128) NOT NULL COMMENT '活动名称',
  `activity_type` varchar(32) NOT NULL COMMENT '活动类型',
  `activity_status` varchar(32) NOT NULL COMMENT '活动状态',
  `start_at` datetime DEFAULT NULL COMMENT '开始时间',
  `end_at` datetime DEFAULT NULL COMMENT '结束时间',
  `rule_payload_json` json DEFAULT NULL COMMENT '规则配置',
  `banner_url` varchar(512) DEFAULT NULL COMMENT '活动Banner',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  KEY `idx_store_status` (`store_id`, `activity_status`),
  KEY `idx_store_time` (`store_id`, `start_at`, `end_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='营销活动表';

CREATE TABLE IF NOT EXISTS `cdd_marketing_activity_product` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `activity_id` bigint NOT NULL COMMENT '活动ID',
  `product_id` bigint NOT NULL COMMENT '商品ID',
  `sku_id` bigint DEFAULT NULL COMMENT 'SKU ID',
  `activity_price` decimal(10,2) DEFAULT NULL COMMENT '活动价',
  `sort_order` int NOT NULL DEFAULT '0' COMMENT '排序号',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  KEY `idx_activity_id` (`activity_id`),
  KEY `idx_product_id` (`product_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='活动商品绑定表';

CREATE TABLE IF NOT EXISTS `cdd_marketing_recommend_rule` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `merchant_id` bigint NOT NULL COMMENT '商家ID',
  `store_id` bigint NOT NULL COMMENT '店铺ID',
  `rule_name` varchar(128) NOT NULL COMMENT '推荐规则名称',
  `scene_code` varchar(64) NOT NULL COMMENT '场景编码',
  `rule_payload_json` json DEFAULT NULL COMMENT '规则配置',
  `status` varchar(32) NOT NULL COMMENT '状态',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  KEY `idx_store_scene` (`store_id`, `scene_code`),
  KEY `idx_store_status` (`store_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='推荐规则表';

CREATE TABLE IF NOT EXISTS `cdd_marketing_topic_floor` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `merchant_id` bigint NOT NULL COMMENT '商家ID',
  `store_id` bigint NOT NULL COMMENT '店铺ID',
  `topic_name` varchar(128) NOT NULL COMMENT '会场名称',
  `topic_code` varchar(64) NOT NULL COMMENT '会场编码',
  `banner_url` varchar(512) DEFAULT NULL COMMENT '会场头图',
  `floor_payload_json` json DEFAULT NULL COMMENT '楼层配置',
  `status` varchar(32) NOT NULL COMMENT '状态',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_store_topic_code_deleted` (`store_id`, `topic_code`, `deleted`),
  KEY `idx_store_status` (`store_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='专题会场配置表';

CREATE TABLE IF NOT EXISTS `cdd_report_home_event_daily` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `merchant_id` bigint NOT NULL COMMENT '商家ID',
  `store_id` bigint NOT NULL COMMENT '店铺ID',
  `stat_date` date NOT NULL COMMENT '统计日期',
  `mini_program_id` bigint DEFAULT NULL COMMENT '小程序ID',
  `page_view_count` bigint NOT NULL DEFAULT '0' COMMENT '页面浏览量',
  `visitor_count` bigint NOT NULL DEFAULT '0' COMMENT '访客数',
  `click_count` bigint NOT NULL DEFAULT '0' COMMENT '点击量',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_store_stat_date_deleted` (`store_id`, `stat_date`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='首页事件日报表';

CREATE TABLE IF NOT EXISTS `cdd_report_order_daily` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `merchant_id` bigint NOT NULL COMMENT '商家ID',
  `store_id` bigint NOT NULL COMMENT '店铺ID',
  `stat_date` date NOT NULL COMMENT '统计日期',
  `order_count` bigint NOT NULL DEFAULT '0' COMMENT '订单数',
  `paid_order_count` bigint NOT NULL DEFAULT '0' COMMENT '支付订单数',
  `gross_amount` decimal(14,2) NOT NULL DEFAULT '0.00' COMMENT '成交总额',
  `refund_amount` decimal(14,2) NOT NULL DEFAULT '0.00' COMMENT '退款总额',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_store_order_stat_date_deleted` (`store_id`, `stat_date`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单日报表';

CREATE TABLE IF NOT EXISTS `cdd_report_product_daily` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `merchant_id` bigint NOT NULL COMMENT '商家ID',
  `store_id` bigint NOT NULL COMMENT '店铺ID',
  `stat_date` date NOT NULL COMMENT '统计日期',
  `product_id` bigint NOT NULL COMMENT '商品ID',
  `sku_id` bigint DEFAULT NULL COMMENT 'SKU ID',
  `view_count` bigint NOT NULL DEFAULT '0' COMMENT '浏览量',
  `sale_count` bigint NOT NULL DEFAULT '0' COMMENT '销量',
  `sale_amount` decimal(14,2) NOT NULL DEFAULT '0.00' COMMENT '销售额',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_store_product_stat_date_deleted` (`store_id`, `product_id`, `stat_date`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商品日报表';

CREATE TABLE IF NOT EXISTS `cdd_metric_merchant_dashboard` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `merchant_id` bigint NOT NULL COMMENT '商家ID',
  `store_id` bigint NOT NULL COMMENT '店铺ID',
  `snapshot_time` datetime NOT NULL COMMENT '快照时间',
  `dashboard_payload_json` json NOT NULL COMMENT '看板快照',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  KEY `idx_store_snapshot_time` (`store_id`, `snapshot_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商家看板快照表';

CREATE TABLE IF NOT EXISTS `cdd_metric_platform_dashboard` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `snapshot_time` datetime NOT NULL COMMENT '快照时间',
  `dashboard_payload_json` json NOT NULL COMMENT '平台看板快照',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  KEY `idx_snapshot_time` (`snapshot_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='平台看板快照表';

CREATE TABLE IF NOT EXISTS `cdd_auth_account` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `account_name` varchar(64) NOT NULL COMMENT '账号名',
  `display_name` varchar(64) NOT NULL COMMENT '显示名称',
  `mobile` varchar(32) DEFAULT NULL COMMENT '手机号',
  `email` varchar(128) DEFAULT NULL COMMENT '邮箱',
  `password_hash` varchar(256) DEFAULT NULL COMMENT '密码哈希',
  `account_type` varchar(32) NOT NULL COMMENT '账号类型',
  `status` varchar(32) NOT NULL COMMENT '状态',
  `last_login_at` datetime DEFAULT NULL COMMENT '最后登录时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_account_name_deleted` (`account_name`, `deleted`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='认证账号表';

CREATE TABLE IF NOT EXISTS `cdd_auth_role` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `role_code` varchar(64) NOT NULL COMMENT '角色编码',
  `role_name` varchar(128) NOT NULL COMMENT '角色名称',
  `role_type` varchar(32) NOT NULL COMMENT '角色类型',
  `status` varchar(32) NOT NULL COMMENT '状态',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_role_code_deleted` (`role_code`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='角色定义表';

CREATE TABLE IF NOT EXISTS `cdd_auth_permission` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `permission_code` varchar(64) NOT NULL COMMENT '权限编码',
  `permission_name` varchar(128) NOT NULL COMMENT '权限名称',
  `permission_group` varchar(64) DEFAULT NULL COMMENT '权限分组',
  `status` varchar(32) NOT NULL COMMENT '状态',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_permission_code_deleted` (`permission_code`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='权限点定义表';

CREATE TABLE IF NOT EXISTS `cdd_auth_role_permission` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `role_id` bigint NOT NULL COMMENT '角色ID',
  `permission_id` bigint NOT NULL COMMENT '权限ID',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_role_permission_deleted` (`role_id`, `permission_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='角色权限关系表';

CREATE TABLE IF NOT EXISTS `cdd_audit_log` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `operator_id` bigint DEFAULT NULL COMMENT '操作人ID',
  `operator_name` varchar(64) DEFAULT NULL COMMENT '操作人名称',
  `operator_type` varchar(32) DEFAULT NULL COMMENT '操作人类型',
  `biz_type` varchar(64) NOT NULL COMMENT '业务类型',
  `biz_id` varchar(64) DEFAULT NULL COMMENT '业务标识',
  `action` varchar(64) NOT NULL COMMENT '操作动作',
  `content` text COMMENT '审计内容',
  `ip_address` varchar(64) DEFAULT NULL COMMENT 'IP地址',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  KEY `idx_biz_type_id` (`biz_type`, `biz_id`),
  KEY `idx_operator_id` (`operator_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='审计日志表';

CREATE TABLE IF NOT EXISTS `cdd_config_feature_switch` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `switch_code` varchar(64) NOT NULL COMMENT '开关编码',
  `switch_name` varchar(128) NOT NULL COMMENT '开关名称',
  `switch_scope` varchar(32) NOT NULL COMMENT '作用范围',
  `default_value` varchar(32) NOT NULL COMMENT '默认值',
  `status` varchar(32) NOT NULL COMMENT '状态',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_switch_code_deleted` (`switch_code`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='功能开关定义表';

CREATE TABLE IF NOT EXISTS `cdd_config_feature_switch_value` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `switch_id` bigint NOT NULL COMMENT '开关ID',
  `scope_type` varchar(32) NOT NULL COMMENT '范围类型',
  `scope_object_id` bigint NOT NULL COMMENT '对象ID',
  `switch_value` varchar(32) NOT NULL COMMENT '开关值',
  `effective_at` datetime DEFAULT NULL COMMENT '生效时间',
  `expired_at` datetime DEFAULT NULL COMMENT '失效时间',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_switch_scope_deleted` (`switch_id`, `scope_type`, `scope_object_id`, `deleted`),
  KEY `idx_scope_object` (`scope_type`, `scope_object_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='功能开关实例值表';

CREATE TABLE IF NOT EXISTS `cdd_config_preset_rule` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `rule_code` varchar(64) NOT NULL COMMENT '规则编码',
  `rule_name` varchar(128) NOT NULL COMMENT '规则名称',
  `rule_type` varchar(32) NOT NULL COMMENT '规则类型',
  `rule_payload_json` json DEFAULT NULL COMMENT '规则内容',
  `status` varchar(32) NOT NULL COMMENT '状态',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_rule_code_deleted` (`rule_code`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='预置规则表';

CREATE TABLE IF NOT EXISTS `cdd_config_kv` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `config_group` varchar(64) NOT NULL COMMENT '配置分组',
  `config_key` varchar(128) NOT NULL COMMENT '配置键',
  `config_value` text COMMENT '配置值',
  `config_desc` varchar(512) DEFAULT NULL COMMENT '配置说明',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_group_key_deleted` (`config_group`, `config_key`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='通用配置表';

CREATE TABLE IF NOT EXISTS `cdd_config_id_segment` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `biz_code` varchar(64) NOT NULL COMMENT '业务编码',
  `current_max_id` bigint NOT NULL DEFAULT '0' COMMENT '当前最大ID',
  `step_size` int NOT NULL DEFAULT '1000' COMMENT '步长',
  `segment_desc` varchar(256) DEFAULT NULL COMMENT '号段说明',
  `created_by` bigint DEFAULT NULL COMMENT '创建人',
  `updated_by` bigint DEFAULT NULL COMMENT '更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记',
  `version` bigint NOT NULL DEFAULT '0' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_biz_code_deleted` (`biz_code`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='应用侧发号号段表';

SET FOREIGN_KEY_CHECKS = 1;
